# Generated by Django 5.2.17 on 2026-09-11 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_clan_clan_type_valid_and_more'),
        ('actions', '0002_actionlog_campaign_contribution'),
        ('campaigns', '0002_campaign_campaign_scope_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actionlog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['APPROVED', 'PENDING_AUDIT', 'REJECTED'])), name='action_log_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='actionmaster',
            constraint=models.CheckConstraint(condition=models.Q(('validation_mode__in', ['DECLARATIVE_BUTTON', 'PHOTO'])), name='action_validation_mode_valid'),
        ),
    ]
