# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_align_approved_validation_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actioncategory",
            table="actions_action_category",
        ),
        migrations.AlterModelTable(
            name="actionlog",
            table="actions_action_log",
        ),
        migrations.AlterModelTable(
            name="actionlogmissioncontribution",
            table="actions_action_log_mission_contribution",
        ),
        migrations.AlterModelTable(
            name="actionmaster",
            table="actions_action_master",
        ),
    ]
