# Generated by Django 5.2.17 on 2026-09-29 13:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_alter_actioncategory_table_alter_actionlog_table_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("points_cost", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "actions_reward",
                "indexes": [
                    models.Index(
                        fields=["is_active", "points_cost"],
                        name="reward_active_cost_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("points_cost__gt", 0)),
                        name="reward_points_cost_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock__gte", 0)),
                        name="reward_stock_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points_spent", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="actions.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "actions_reward_redemption",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="redemption_user_created_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="redemption_status_created_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("points_spent__gt", 0)),
                        name="redemption_points_spent_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["COMPLETED", "CANCELLED"])),
                        name="redemption_status_valid",
                    ),
                ],
            },
        ),
    ]
