# Generated by Django 5.2.17 on 2026-10-01 09:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_alter_actioncategory_table_alter_actionlog_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeableItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FRAME", "Avatar Frame"),
                            ("BADGE", "Profile Badge"),
                            ("THEME", "Profile Theme"),
                            ("TITLE", "User Title"),
                            ("OTHER", "Other"),
                        ],
                        default="FRAME",
                        max_length=20,
                    ),
                ),
                ("points_cost", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "actions_exchangeable_item",
                "indexes": [
                    models.Index(
                        fields=["is_active", "points_cost"],
                        name="exchangeable_active_cost_idx",
                    ),
                    models.Index(fields=["key"], name="exchangeable_key_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("points_cost__gt", 0)),
                        name="exchangeable_points_cost_positive",
                    )
                ],
            },
        ),
    ]
