# Generated by Django 5.2.17 on 2026-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_add_one_cosmetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeableitem',
            name='category',
            field=models.CharField(choices=[('FRAME', 'Avatar Frame'), ('BACKGROUND', 'Profile Background'), ('THEME', 'Profile Theme'), ('OTHER', 'Other')], default='FRAME', max_length=20),
        ),
    ]
