# Generated by Django 5.2.17 on 2026-10-02 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0006_actionlog_is_shared_publicly"),
        ("actions", "0008_alter_exchangeableitem_category"),
    ]

    operations = []
