# Generated by Django 5.2.17 on 2026-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_date_joined"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="clan",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["INSTITUTIONAL", "PRIVATE"])),
                name="clan_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="clan",
            constraint=models.CheckConstraint(
                condition=models.Q(("privacy__in", ["PUBLIC", "PRIVATE_INVITE"])),
                name="clan_privacy_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="clanmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["LEADER", "MEMBER"])),
                name="membership_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["STUDENT", "STAFF", "ADMIN"])),
                name="user_role_valid",
            ),
        ),
    ]
