# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_options_clan_clan_type_valid_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="clan",
            table="accounts_clan",
        ),
        migrations.AlterModelTable(
            name="clanmembership",
            table="accounts_clan_membership",
        ),
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="accounts_user_profile",
        ),
    ]
