# Generated by Django 5.2.17 on 2026-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_clan_table_alter_clanmembership_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="microsoft_oid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="microsoft_group_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
