# Generated by Django 5.2.17 on 2026-09-18 14:04

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_clan_table_alter_clanmembership_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clan",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="clan",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("visibility__in", ["PUBLIC", "PRIVATE"])),
                name="profile_visibility_valid",
            ),
        ),
    ]
