# Generated by Django 5.2.17 on 2026-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_clan_options_alter_clan_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="available_points",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_points__gte", 0)),
                name="profile_available_points_nonnegative",
            ),
        ),
    ]
