# Generated by Django 5.2.17 on 2026-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_nickname_userprofile_available_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clan",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="clan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name",),
                name="clan_name_unique_when_alive",
            ),
        ),
    ]
