# Generated by Django 5.2.17 on 2026-09-22 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_microsoft_identity"),
        ("accounts", "0007_clan_name_unique_when_alive"),
    ]

    operations = []
