# Generated by Django 5.2.17 on 2026-09-26 20:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_merge_microsoft_identity_and_clan_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("low_user", models.UUIDField(editable=False)),
                ("high_user", models.UUIDField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addressee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_friendship",
                "indexes": [
                    models.Index(
                        fields=["addressee", "status"], name="friendship_addr_st_idx"
                    ),
                    models.Index(
                        fields=["requester", "status"], name="friendship_req_st_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("requester", models.F("addressee")), _negated=True
                        ),
                        name="friendship_not_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("low_user__lt", models.F("high_user"))),
                        name="friendship_pair_ordered",
                    ),
                    models.UniqueConstraint(
                        fields=("low_user", "high_user"), name="friendship_pair_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["PENDING", "ACCEPTED", "REJECTED"])
                        ),
                        name="friendship_status_valid",
                    ),
                ],
            },
        ),
    ]
