# Generated by Django 5.2.17 on 2026-09-29 14:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_merge_microsoft_identity_and_clan_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoleAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("STAFF", "Staff"),
                            ("ADMIN", "Administrator"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("STAFF", "Staff"),
                            ("ADMIN", "Administrator"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_role_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_role_audit",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("previous_role__in", ["STUDENT", "STAFF", "ADMIN"])
                        ),
                        name="user_role_audit_previous_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("new_role__in", ["STUDENT", "STAFF", "ADMIN"])
                        ),
                        name="user_role_audit_new_role_valid",
                    ),
                ],
            },
        ),
    ]
