# Generated by Django 5.2.17 on 2026-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_profile_editing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unlocked_cosmetics",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
