# Generated by Django 5.2.17 on 2026-10-02 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_friendship"),
        ("accounts", "0012_merge_role_audit_and_public_ranking"),
    ]

    operations = []
