# Generated by Django 5.2.17 on 2026-10-02 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_userprofile_unlocked_cosmetics"),
        ("accounts", "0013_merge_friendship_and_role_audit_ranking"),
    ]

    operations = []
