# Generated by Django 5.2.17 for the T9a schema draft.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("scope", models.CharField(choices=[("GLOBAL", "Global"), ("PRIVATE", "Private clan")], max_length=10)),
                ("status", models.CharField(choices=[("PROMOTION", "Promotion"), ("IN_PROGRESS", "In progress"), ("FINISHED", "Finished")], default="PROMOTION", max_length=20)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("podium_snapshot", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_campaigns", to=settings.AUTH_USER_MODEL)),
                ("target_clan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="target_campaigns", to="accounts.clan")),
            ],
            options={
                "indexes": [models.Index(fields=["status", "start_date", "end_date"], name="campaign_window_idx")],
                "constraints": [
                    models.CheckConstraint(condition=Q(("end_date__gt", F("start_date"))), name="campaign_end_after_start"),
                    models.CheckConstraint(condition=(Q(("scope", "GLOBAL"), ("target_clan__isnull", True)) | Q(("scope", "PRIVATE"), ("target_clan__isnull", False))), name="campaign_scope_target_clan_consistent"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_count", models.PositiveIntegerField()),
                ("action", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="missions", to="actions.actionmaster")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="missions", to="campaigns.campaign")),
            ],
            options={"constraints": [models.CheckConstraint(condition=Q(("target_count__gt", 0)), name="mission_target_positive")]},
        ),
        migrations.CreateModel(
            name="CampaignParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="participants", to="campaigns.campaign")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="campaign_participations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("campaign", "user"), name="campaign_participant_unique")]},
        ),
        migrations.CreateModel(
            name="UserMissionProgress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("current_count", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="user_progress", to="campaigns.mission")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="mission_progress", to=settings.AUTH_USER_MODEL)),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("user", "mission"), name="user_mission_progress_unique")]},
        ),
    ]
