# Generated by Django 5.2.17 on 2026-09-12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_mission_action_master_column"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="campaign",
            table="campaigns_campaign",
        ),
        migrations.AlterModelTable(
            name="campaignparticipant",
            table="campaigns_campaign_participant",
        ),
        migrations.AlterModelTable(
            name="mission",
            table="campaigns_mission",
        ),
        migrations.AlterModelTable(
            name="usermissionprogress",
            table="campaigns_user_mission_progress",
        ),
    ]
