# Generated by Django 5.2.17 on 2026-09-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_alter_actioncategory_table_alter_actionlog_table_and_more"),
        (
            "campaigns",
            "0004_alter_campaign_table_alter_campaignparticipant_table_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mission",
            constraint=models.UniqueConstraint(
                fields=("campaign", "action"), name="mission_campaign_action_unique"
            ),
        ),
    ]
