# Generated by Django 5.2.17 on 2026-09-27 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_merge_microsoft_identity_and_clan_updates"),
        ("campaigns", "0005_mission_campaign_action_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approval_status__in", ["PENDING", "APPROVED", "REJECTED"])
                ),
                name="campaign_approval_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "PRIVATE"), _negated=True),
                    ("approval_status", "APPROVED"),
                    _connector="OR",
                ),
                name="campaign_private_always_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("approval_status", "REJECTED"), _negated=True),
                    models.Q(("rejection_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="campaign_rejection_has_reason",
            ),
        ),
    ]
