# Generated by Django 5.2.17 on 2026-09-15 14:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("AUDIT_REJECT", "Photo audit rejected"),
                            ("BADGE_EARNED", "Badge earned"),
                            ("CAMPAIGN_INVITE", "Campaign invitation"),
                            ("MISSION_COMPLETED", "Mission completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notification_user_read_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "notification_type__in",
                                [
                                    "AUDIT_REJECT",
                                    "BADGE_EARNED",
                                    "CAMPAIGN_INVITE",
                                    "MISSION_COMPLETED",
                                ],
                            )
                        ),
                        name="notification_type_valid",
                    )
                ],
            },
        ),
    ]
