# Generated by Django 5.2.17 on 2026-10-01 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_type_valid",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("AUDIT_APPROVED", "Photo audit approved"),
                    ("AUDIT_REJECT", "Photo audit rejected"),
                    ("BADGE_EARNED", "Badge earned"),
                    ("CAMPAIGN_INVITE", "Campaign invitation"),
                    ("MISSION_COMPLETED", "Mission completed"),
                    ("SOCIAL_FOLLOW", "New follower"),
                    ("SYSTEM", "System announcement"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "notification_type__in",
                        [
                            "AUDIT_APPROVED",
                            "AUDIT_REJECT",
                            "BADGE_EARNED",
                            "CAMPAIGN_INVITE",
                            "MISSION_COMPLETED",
                            "SOCIAL_FOLLOW",
                            "SYSTEM",
                        ],
                    )
                ),
                name="notification_type_valid",
            ),
        ),
    ]
