# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_types_audit_approved_social_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelManagers(
            name="notification",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
