name: Deploy - test

on:
  push:
    branches: [test]

jobs:
  deploy:
    if: vars.CLOUD_DEPLOYMENT_ENABLED == 'true'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: test
      build: false
    secrets: inherit
