name: Precommit

on:
  push:
  pull_request:

jobs:
  commit-lint:
    name: Validate Conventional Commit PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Valida que el título del PR cumpla la convención (feat:, fix:, chore:, etc.)
      - name: Validate PR Title
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: "^([A-Za-z]+)(?:\\(([^)]+)\\))?[:/]\\s*(.+)$"
          headerPatternCorrespondence: |
            type
            scope
            subject
          types: |
            feat
            Feat
            fix
            Fix
            docs
            Docs
            style
            Style
            refactor
            Refactor
            perf
            Perf
            test
            Test
            build
            Build
            ci
            Ci
            chore
            Chore
            revert
            Revert
          requireScope: false
